spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${USER_DB_NAME}
    username: ${USER_DB_USER}
    password: ${USER_DB_PASSWORD}

    hikari:
      pool-name: UserServiceHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

cognito:
  region: us-east-1
  userPoolId: us-east-1_TOZbkz8xq
  audience: 1fmj0q99hsrk25s8llprks1scp

hr:
  base-url: ${HR_BASE_URL:http://localhost:8082}
